// lib/languages.ts
// Liste complète des langues disponibles pour les comédiens
// Utilisé dans : inscription, édition de profil, et filtres de recherche

// Langues les plus courantes (affichées en premier)
export const COMMON_LANGUAGES = [
  "Français",
  "Anglais",
  "Espagnol",
  "Allemand",
  "Italien",
  "Portugais",
  "Néerlandais",
  "Arabe",
  "Chinois",
  "Russe",
  "Japonais",
  "Polonais",
  "Turc",
  "Grec",
  "Hindi",
  "Coréen"
]

export const LANGUAGES = [
  "Anglais",
  "Français",
  "Néerlandais",
  "Abkhaze",
  "Aceh",
  "Acoli",
  "Adangme",
  "Adyghéen",
  "Afar",
  "Afrihili",
  "Afrikaans",
  "Aghem",
  "Aïnou",
  "Akan",
  "Akkadien",
  "Akoose",
  "Alabama",
  "Albanais",
  "Aléoute",
  "Allemand",
  "Allemand autrichien",
  "Allemand palatin",
  "Allemand suisse",
  "Altaï du Sud",
  "Amazighe de l'Atlas central",
  "Amazighe standard marocain",
  "Amharique",
  "Ancien anglais",
  "Ancien français",
  "Ancien haut allemand",
  "Ancien irlandais",
  "Angika",
  "Anglais américain",
  "Anglais australien",
  "Anglais britannique",
  "Anglais canadien",
  "Ao",
  "Arabe",
  "Arabe algérien",
  "Arabe égyptien",
  "Arabe marocain",
  "Arabe najdi",
  "Arabe standard moderne",
  "Arabe tchadien",
  "Arabe tunisien",
  "Aragonais",
  "Araméen",
  "Araméen samaritain",
  "Araona",
  "Arapaho",
  "Arawak",
  "Arménien",
  "Assamais",
  "Assou",
  "Asturien",
  "Atsam",
  "Avar",
  "Avestique",
  "Awadhi",
  "Aymara",
  "Azéri",
  "Bachkir",
  "Badaga",
  "Bafia",
  "Bafut",
  "Bakhtiari",
  "Balinais",
  "Baloutchi",
  "Baloutchi occidental",
  "Bambara",
  "Bamoun",
  "Banjar",
  "Bas-allemand",
  "Bas-prussien",
  "Bas-saxon néerlandais",
  "Bas-silésien",
  "Bas-sorabe",
  "Basque",
  "Bassa",
  "Batak toba",
  "Bavarois",
  "Bedja",
  "Bemba",
  "Béna",
  "Bengali",
  "Betawi",
  "Bhojpuri",
  "Bichelamar",
  "Biélorusse",
  "Bikol",
  "Bini",
  "Birman",
  "Bishnupriya",
  "Blin",
  "Bodo",
  "Bosniaque",
  "Boulou",
  "Bouriate",
  "Brahoui",
  "Braj",
  "Breton",
  "Bugi",
  "Bulgare",
  "Caddo",
  "Caingangue",
  "Cantonais",
  "Capiznon",
  "Capverdien",
  "Carélien",
  "Caribe",
  "Catalan",
  "Cayuga",
  "Cebuano",
  "Chakma",
  "Chambala",
  "Chamorro",
  "Cherokee",
  "Cheyenne",
  "Chibcha",
  "Chinois",
  "Chinois littéraire",
  "Chinois simplifié",
  "Chinois traditionnel",
  "Chipewyan",
  "Chleuh",
  "Choctaw",
  "Chuuk",
  "Cinghalais",
  "Cisena",
  "Comorien",
  "Copte",
  "Coréen",
  "Cornique",
  "Corse",
  "Cree",
  "Creek",
  "Créole haïtien",
  "Créole jamaïcain",
  "Créole louisianais",
  "Créole mauricien",
  "Créole seychellois",
  "Croate",
  "Dakota",
  "Danois",
  "Dargwa",
  "Dari",
  "Dari zoroastrien",
  "Dazaga",
  "Delaware",
  "Dinka",
  "Diola-fogny",
  "Dioula",
  "Dogri",
  "Dogrib",
  "Douala",
  "Dusun central",
  "Dzongkha",
  "Écossais",
  "Éfik",
  "Égyptien ancien",
  "Ékadjouk",
  "Élamite",
  "Embou",
  "Émilien",
  "Erzya",
  "Esclave",
  "Espagnol",
  "Espéranto",
  "Estonien",
  "Estrémègne",
  "European Spanish",
  "Éwé",
  "Éwondo",
  "Fang",
  "Fanti",
  "Féroïen",
  "Fidjien",
  "Filipino",
  "Finnois",
  "Finnois tornédalien",
  "Flamand",
  "Flamand occidental",
  "Fon",
  "Français cadien",
  "Français canadien",
  "Français suisse",
  "Francique ripuaire",
  "Franconien du Main",
  "Francoprovençal",
  "Frioulan",
  "Frison du Nord",
  "Frison occidental",
  "Frison oriental",
  "Ga",
  "Gaélique écossais",
  "Gagaouze",
  "Galicien",
  "Gallois",
  "Gan",
  "Ganda",
  "Gayo",
  "Gbaya",
  "Géorgien",
  "Ghomala",
  "Gilaki",
  "Gilbertin",
  "Gondi",
  "Gorontalo",
  "Gothique",
  "Goudjerati",
  "Grebo",
  "Grec",
  "Grec ancien",
  "Groenlandais",
  "Guarani",
  "Guègue",
  "Guèze",
  "Gurenne",
  "Gusii",
  "Gwichʼin",
  "Haida",
  "Hakka",
  "Haoussa",
  "Haut-sorabe",
  "Hawaien",
  "Hébreu",
  "Héréro",
  "Hiligaynon",
  "Hindi",
  "Hindi fidjien",
  "Hiri motu",
  "Hittite",
  "Hmong",
  "Hongrois",
  "Hupa",
  "Iakoute",
  "Iban",
  "Ibibio",
  "Ido",
  "Igbo",
  "Ilokano",
  "Indonésien",
  "Ingouche",
  "Ingrien",
  "Interlingua",
  "Interlingue",
  "Inuktitut",
  "Inupiaq",
  "Irlandais",
  "Islandais",
  "Italien",
  "Japonais",
  "Jargon chinook",
  "Javanais",
  "Jju",
  "Judéo-arabe",
  "Judéo-persan",
  "Jute",
  "K'iche'",
  "Kabardin",
  "Kabyle",
  "Kachin",
  "Kachoube",
  "Kako",
  "Kalendjin",
  "Kalmouk",
  "Kamba",
  "Kanembou",
  "Kannada",
  "Kanouri",
  "Karakalpak",
  "Karatchaï balkar",
  "Kashmiri",
  "Kawi",
  "Kazakh",
  "Kényang",
  "Khasi",
  "Khmer",
  "Khotanais",
  "Khowar",
  "Kiga",
  "Kikuyu",
  "Kimboundou",
  "Kinaray-a",
  "Kirghize",
  "Kirmanjki",
  "Klingon",
  "Kom",
  "Komi",
  "Komi-permiak",
  "Kongo",
  "Konkani",
  "Konkani de Goa",
  "Koro",
  "Kosraéen",
  "Kotava",
  "Kouanyama",
  "Koumyk",
  "Kourroukh",
  "Koyra chiini",
  "Koyraboro senni",
  "Kpellé",
  "Krio",
  "Kurde",
  "Kurde du Sud",
  "Kutenai",
  "Kwasio",
  "Ladino",
  "Lahnda",
  "Lakota",
  "Lamba",
  "Langi",
  "Langue des signes américaine",
  "Langue indéterminée",
  "Lao",
  "Latgalien",
  "Latin",
  "Latin American Spanish",
  "Laze",
  "Letton",
  "Lezghien",
  "Ligure",
  "Limbourgeois",
  "Lingala",
  "Lingua franca nova",
  "Lituanien",
  "Livonien",
  "Lojban",
  "Lombard",
  "Lori du Nord",
  "Lozi",
  "Luba-katanga",
  "Luba-lulua",
  "Luhya",
  "Luiseño",
  "Lunda",
  "Luo",
  "Lushaï",
  "Luxembourgeois",
  "Maba",
  "Macédonien",
  "Madouraï",
  "Mafa",
  "Magahi",
  "Maithili",
  "Makassar",
  "Makhuwa-meetto",
  "Makondé",
  "Malais",
  "Malayalam",
  "Maldivien",
  "Malgache",
  "Maltais",
  "Mandan",
  "Mandchou",
  "Mandingue",
  "Manipuri",
  "Mannois",
  "Maori",
  "Mapuche",
  "Marathe",
  "Mari",
  "Mari occidental",
  "Marshallais",
  "Marwarî",
  "Massaï",
  "Matchamé",
  "Mazandérani",
  "Médumba",
  "Mendé",
  "Mentawaï",
  "Mérou",
  "Méta'",
  "Mexican Spanish",
  "Micmac",
  "Minangkabau",
  "Mingrélien",
  "Minnan",
  "Mirandais",
  "Mohawk",
  "Moksa",
  "Moldave",
  "Mongo",
  "Mongol",
  "Monténégrin",
  "Moré",
  "Moundang",
  "Moyen anglais",
  "Moyen français",
  "Moyen haut-allemand",
  "Moyen irlandais",
  "Moyen néerlandais",
  "Multilingue",
  "Myènè",
  "N'ko",
  "Nama",
  "Napolitain",
  "Nauruan",
  "Navaho",
  "Ndébélé du Nord",
  "Ndébélé du Sud",
  "Ndonga",
  "Népalais",
  "Newari",
  "Newarî classique",
  "Ngambay",
  "Ngiemboon",
  "Ngomba",
  "Nheengatu",
  "Nias",
  "Niuéen",
  "Nogaï",
  "Norvégien",
  "Norvégien bokmål",
  "Norvégien nynorsk",
  "Novial",
  "Nuer",
  "Nyamwezi",
  "Nyanja",
  "Nyankolé",
  "Nyoro",
  "Nzema",
  "Occitan",
  "Ojibwa",
  "Oriya",
  "Oromo",
  "Osage",
  "Ossète",
  "Oudmourte",
  "Ougaritique",
  "Ouïghour",
  "Oumboundou",
  "Ourdou",
  "Ouzbek",
  "Pachto",
  "Pahlavi",
  "Palau",
  "Pali",
  "Pampangan",
  "Pangasinan",
  "Papiamento",
  "Pendjabi",
  "Pennsilvänisch",
  "Persan",
  "Persan ancien",
  "Peul",
  "Phénicien",
  "Picard",
  "Pidgin nigérian",
  "Piémontais",
  "Pohnpei",
  "Polonais",
  "Pontique",
  "Portugais",
  "Portugais brésilien",
  "Portugais européen",
  "Provençal ancien",
  "Prussien",
  "Quechua",
  "Quichua du Haut-Chimborazo",
  "Racine",
  "Rajasthani",
  "Rapanui",
  "Rarotongien",
  "Rifain",
  "Romagnol",
  "Romanche",
  "Romani",
  "Rombo",
  "Rotuman",
  "Roumain",
  "Roundi",
  "Roviana",
  "Russe",
  "Ruthène",
  "Rwa",
  "Rwanda",
  "Saho",
  "Sambourou",
  "Sami d'Inari",
  "Sami de Lule",
  "Sami du Nord",
  "Sami du Sud",
  "Sami skolt",
  "Samoan",
  "Samogitien",
  "Sandawe",
  "Sangho",
  "Sangu",
  "Sans contenu linguistique",
  "Sanskrit",
  "Santal",
  "Sarde",
  "Sarde sassarais",
  "Sasak",
  "Saterlandais",
  "Saurashtra",
  "Sélayar",
  "Selkoupe",
  "Seneca",
  "Serbe",
  "Serbo-croate",
  "Sérèr",
  "Séri",
  "Shan",
  "Shona",
  "Sicilien",
  "Sidamo",
  "Siksika",
  "Silésien",
  "Sindhi",
  "Slavon d'église",
  "Slovaque",
  "Slovène",
  "Soga",
  "Sogdien",
  "Somali",
  "Soninké",
  "Sorani",
  "Sotho du Nord",
  "Sotho du Sud",
  "Soukouma",
  "Soundanais",
  "Soussou",
  "Sranan tongo",
  "Suédois",
  "Suisse allemand",
  "Sumérien",
  "Swahili",
  "Swahili du Congo",
  "Swati",
  "Symboles Bliss",
  "Syriaque",
  "Syriaque classique",
  "Tadjik",
  "Tagalog",
  "Tahitien",
  "Taita",
  "Talysh",
  "Tamacheq",
  "Tamoul",
  "Taroko",
  "Tasawaq",
  "Tatar",
  "Tati caucasien",
  "Tchaghataï",
  "Tchèque",
  "Tchétchène",
  "Tchouvache",
  "Télougou",
  "Temne",
  "Tereno",
  "Teso",
  "Tetum",
  "Thaï",
  "Tibétain",
  "Tigré",
  "Tigrigna",
  "Tiv",
  "Tlingit",
  "Tok pisin",
  "Tokelau",
  "Tonga nyasa",
  "Tonguien",
  "Toulou",
  "Toumbouka",
  "Touroyc",
  "Touvain",
  "Tsakhour",
  "Tsakonien",
  "Tsimshian",
  "Tsonga",
  "Tswana",
  "Turc",
  "Turc de Crimée",
  "Turc ottoman",
  "Turkmène",
  "Tuvalu",
  "Twi",
  "Tyap",
  "Ukrainien",
  "Vaï",
  "Valaque",
  "Venda",
  "Vénitien",
  "Vepse",
  "Vietnamien",
  "Vieux norrois",
  "Volapük",
  "Võro",
  "Vote",
  "Vunjo",
  "Walamo",
  "Wallon",
  "Walser",
  "Waray",
  "Warlpiri",
  "Washo",
  "Wayuu",
  "Wolof",
  "Wu",
  "Xhosa",
  "Xiang",
  "Yangben",
  "Yao",
  "Yapois",
  "Yemba",
  "Yi du Sichuan",
  "Yiddish",
  "Yoruba",
  "Youpik central",
  "Zapotèque",
  "Zarma",
  "Zazaki",
  "Zélandais",
  "Zenaga",
  "Zhuang",
  "Zoulou",
  "Zuñi"
]

// Langues moins courantes (toutes sauf les courantes)
const OTHER_LANGUAGES = LANGUAGES.filter(lang => !COMMON_LANGUAGES.includes(lang))

// Options formatées pour les selects avec langues courantes en premier
export const LANGUAGE_OPTIONS = [
  { value: '', label: 'Indifférent' },
  // Langues courantes en premier
  ...COMMON_LANGUAGES.map(lang => ({ value: lang, label: lang })),
  // Séparateur
  { value: '', label: '──────────', disabled: true },
  // Toutes les autres langues
  ...OTHER_LANGUAGES.map(lang => ({ value: lang, label: lang }))
]

// Pour les formulaires d'inscription/édition : langues courantes + toutes les autres
export const LANGUAGE_SELECT_OPTIONS = {
  common: COMMON_LANGUAGES,
  other: OTHER_LANGUAGES,
  all: LANGUAGES
}
