#!/bin/bash

echo "🚀 MIGRATION DE LA BASE DE DONNÉES - ADK KASTING"
echo "==============================================="
echo ""
echo "⚠️  IMPORTANT: Testez d'abord sur une copie de votre base !"
echo ""
echo "1. Ouvrez votre projet Supabase: https://supabase.com"
echo "2. Allez dans 'SQL Editor'"
echo "3. Copiez-collez le contenu du fichier migration_add_missing_fields.sql"
echo "4. Exécutez la migration"
echo ""
echo "📋 La migration va ajouter ces colonnes à votre table 'comediens':"
echo "   ✅ Informations contact: phone_fixe, street, zip_code, country"
echo "   ✅ Langues avec niveaux: languages_fluent, languages_notions"  
echo "   ✅ Photos multiples: photos (array)"
echo "   ✅ Vidéos: showreel_url, video_1_url, video_2_url"
echo "   ✅ Agent: agency_name, agent_name, agent_email, agent_phone"
echo "   ✅ Réseaux sociaux: website_url, imdb_url, facebook_url, linkedin_url"
echo "   ✅ Formation: professional_experience, training_diplomas, cv_pdf_url"
echo "   ✅ Compétences: driving_licenses, diverse_skills, desired_activities"
echo ""
echo "📊 Après la migration, vos 9000 profils existants:"
echo "   ✅ Conserveront toutes leurs données actuelles"
echo "   ✅ Auront les nouveaux champs (vides au début)"
echo "   ✅ L'image de profil sera migrée vers photos[0]"
echo ""
echo "🔧 Puis exécutez: npm run update-api"
echo "    pour mettre à jour le code de l'application"
echo ""
read -p "Appuyez sur Entrée pour continuer..."