#!/bin/bash

echo "🔧 Configuration de la base de données pour le système d'authentification ADK"
echo "=========================================================================="

echo ""
echo "📋 Instructions de migration Supabase :"
echo ""
echo "1. Ouvrez votre projet Supabase"
echo "2. Allez dans 'SQL Editor'"
echo "3. Exécutez les commandes suivantes dans l'ordre :"
echo ""

echo "-- 📦 1. Mise à jour de la table comediens pour WordPress"
echo "ALTER TABLE comediens DROP COLUMN IF EXISTS password;"
echo "ALTER TABLE comediens ADD COLUMN IF NOT EXISTS user_pass TEXT;"
echo "ALTER TABLE comediens ALTER COLUMN user_pass DROP NOT NULL;"
echo ""

echo "-- 🔗 2. Ajout de la référence vers Supabase Auth (si pas déjà fait)"
echo "ALTER TABLE comediens ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL;"
echo ""

echo "-- 👤 3. Création de la table des profils utilisateurs"
echo "CREATE TABLE IF NOT EXISTS user_profiles ("
echo "  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,"
echo "  role TEXT NOT NULL DEFAULT 'public' CHECK (role IN ('public', 'comedien', 'admin')),"
echo "  created_at TIMESTAMPTZ DEFAULT NOW(),"
echo "  updated_at TIMESTAMPTZ DEFAULT NOW()"
echo ");"
echo ""

echo "-- 📝 4. Création de la table des commentaires admin"
echo "CREATE TABLE IF NOT EXISTS admin_comments ("
echo "  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,"
echo "  comedien_id UUID REFERENCES comediens(id) ON DELETE CASCADE,"
echo "  admin_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,"
echo "  admin_name TEXT NOT NULL DEFAULT 'Admin',"
echo "  comment TEXT NOT NULL,"
echo "  created_at TIMESTAMPTZ DEFAULT NOW(),"
echo "  updated_at TIMESTAMPTZ DEFAULT NOW()"
echo ");"
echo ""

echo "-- 🚀 5. Création d'un compte admin par défaut"
echo "-- Remplacez 'admin@adk.com' et 'votre-mot-de-passe-admin' par vos vraies valeurs"
echo ""
echo "DO \$\$"
echo "DECLARE"
echo "    admin_user_id UUID;"
echo "BEGIN"
echo "    -- Insérer l'admin dans auth.users (uniquement si n'existe pas)"
echo "    INSERT INTO auth.users (id, email, encrypted_password, email_confirmed_at, created_at, updated_at)"
echo "    VALUES ("
echo "        gen_random_uuid(),"
echo "        'admin@adk.com',"
echo "        crypt('votre-mot-de-passe-admin', gen_salt('bf')),"
echo "        NOW(),"
echo "        NOW(),"
echo "        NOW()"
echo "    )"
echo "    ON CONFLICT (email) DO NOTHING"
echo "    RETURNING id INTO admin_user_id;"
echo ""
echo "    -- Si l'utilisateur existait déjà, récupérer son ID"
echo "    IF admin_user_id IS NULL THEN"
echo "        SELECT id INTO admin_user_id FROM auth.users WHERE email = 'admin@adk.com';"
echo "    END IF;"
echo ""
echo "    -- Créer le profil admin"
echo "    INSERT INTO user_profiles (id, role)"
echo "    VALUES (admin_user_id, 'admin')"
echo "    ON CONFLICT (id) DO UPDATE SET role = 'admin';"
echo "END \$\$;"
echo ""

echo "-- 📊 6. Index pour les performances"
echo "CREATE INDEX IF NOT EXISTS idx_comediens_user_id ON comediens(user_id);"
echo "CREATE INDEX IF NOT EXISTS idx_comediens_email ON comediens(email);"
echo "CREATE INDEX IF NOT EXISTS idx_comediens_user_pass ON comediens(user_pass) WHERE user_pass IS NOT NULL;"
echo "CREATE INDEX IF NOT EXISTS idx_user_profiles_role ON user_profiles(role);"
echo "CREATE INDEX IF NOT EXISTS idx_admin_comments_comedien ON admin_comments(comedien_id);"
echo ""

echo "-- 🔧 7. Fonction de mise à jour automatique des timestamps"
echo "CREATE OR REPLACE FUNCTION update_updated_at_column()"
echo "RETURNS TRIGGER AS \$\$"
echo "BEGIN"
echo "    NEW.updated_at = NOW();"
echo "    RETURN NEW;"
echo "END;"
echo "\$\$ language 'plpgsql';"
echo ""

echo "-- 📅 8. Triggers pour updated_at"
echo "DROP TRIGGER IF EXISTS update_user_profiles_updated_at ON user_profiles;"
echo "CREATE TRIGGER update_user_profiles_updated_at"
echo "    BEFORE UPDATE ON user_profiles"
echo "    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();"
echo ""
echo "DROP TRIGGER IF EXISTS update_comediens_updated_at ON comediens;"
echo "CREATE TRIGGER update_comediens_updated_at"
echo "    BEFORE UPDATE ON comediens"
echo "    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();"
echo ""
echo "DROP TRIGGER IF EXISTS update_admin_comments_updated_at ON admin_comments;"
echo "CREATE TRIGGER update_admin_comments_updated_at"
echo "    BEFORE UPDATE ON admin_comments"
echo "    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();"
echo ""

echo "=========================================================================="
echo "✅ Migration terminée !"
echo ""
echo "🔗 Prochaines étapes :"
echo "1. Modifiez le mot de passe admin dans la commande ci-dessus"
echo "2. Exécutez ces commandes dans Supabase SQL Editor"
echo "3. Vérifiez que vos comédiens WordPress peuvent se connecter"
echo "4. Testez la connexion admin sur /connexion"
echo ""
echo "📋 Notes importantes :"
echo "- Les mots de passe WordPress existants (user_pass) seront respectés"
echo "- Le système créera automatiquement des comptes Supabase Auth lors de la première connexion"
echo "- Les nouveaux utilisateurs utiliseront directement Supabase Auth"
echo "- L'API /api/auth/wordpress-login gère la migration automatique"
echo ""